<?php

namespace Bgaze\BootstrapForm\Support\Html;

/**
 * @method static HtmlElement area(array $attributes = [])
 * @method static HtmlElement base(array $attributes = [])
 * @method static HtmlElement br(array $attributes = [])
 * @method static HtmlElement col(array $attributes = [])
 * @method static HtmlElement embed(array $attributes = [])
 * @method static HtmlElement hr(array $attributes = [])
 * @method static HtmlElement img(array $attributes = [])
 * @method static HtmlElement input(array $attributes = [])
 * @method static HtmlElement link(array $attributes = [])
 * @method static HtmlElement meta(array $attributes = [])
 * @method static HtmlElement param(array $attributes = [])
 * @method static HtmlElement source(array $attributes = [])
 * @method static HtmlElement track(array $attributes = [])
 * @method static HtmlElement wbr(array $attributes = [])
 * @method static HtmlElement a(array $attributes = [])
 * @method static HtmlElement abbr(array $attributes = [])
 * @method static HtmlElement address(array $attributes = [])
 * @method static HtmlElement article(array $attributes = [])
 * @method static HtmlElement aside(array $attributes = [])
 * @method static HtmlElement audio(array $attributes = [])
 * @method static HtmlElement b(array $attributes = [])
 * @method static HtmlElement bdi(array $attributes = [])
 * @method static HtmlElement bdo(array $attributes = [])
 * @method static HtmlElement blockquote(array $attributes = [])
 * @method static HtmlElement body(array $attributes = [])
 * @method static HtmlElement button(array $attributes = [])
 * @method static HtmlElement canvas(array $attributes = [])
 * @method static HtmlElement caption(array $attributes = [])
 * @method static HtmlElement cite(array $attributes = [])
 * @method static HtmlElement code(array $attributes = [])
 * @method static HtmlElement colgroup(array $attributes = [])
 * @method static HtmlElement data(array $attributes = [])
 * @method static HtmlElement datalist(array $attributes = [])
 * @method static HtmlElement dd(array $attributes = [])
 * @method static HtmlElement del(array $attributes = [])
 * @method static HtmlElement details(array $attributes = [])
 * @method static HtmlElement dfn(array $attributes = [])
 * @method static HtmlElement div(array $attributes = [])
 * @method static HtmlElement dl(array $attributes = [])
 * @method static HtmlElement dt(array $attributes = [])
 * @method static HtmlElement em(array $attributes = [])
 * @method static HtmlElement fieldset(array $attributes = [])
 * @method static HtmlElement figcaption(array $attributes = [])
 * @method static HtmlElement figure(array $attributes = [])
 * @method static HtmlElement footer(array $attributes = [])
 * @method static HtmlElement h1(array $attributes = [])
 * @method static HtmlElement h2(array $attributes = [])
 * @method static HtmlElement h3(array $attributes = [])
 * @method static HtmlElement h4(array $attributes = [])
 * @method static HtmlElement h5(array $attributes = [])
 * @method static HtmlElement h6(array $attributes = [])
 * @method static HtmlElement head(array $attributes = [])
 * @method static HtmlElement header(array $attributes = [])
 * @method static HtmlElement hgroup(array $attributes = [])
 * @method static HtmlElement html(array $attributes = [])
 * @method static HtmlElement i(array $attributes = [])
 * @method static HtmlElement iframe(array $attributes = [])
 * @method static HtmlElement ins(array $attributes = [])
 * @method static HtmlElement kbd(array $attributes = [])
 * @method static HtmlElement label(array $attributes = [])
 * @method static HtmlElement legend(array $attributes = [])
 * @method static HtmlElement li(array $attributes = [])
 * @method static HtmlElement map(array $attributes = [])
 * @method static HtmlElement mark(array $attributes = [])
 * @method static HtmlElement meter(array $attributes = [])
 * @method static HtmlElement nav(array $attributes = [])
 * @method static HtmlElement noscript(array $attributes = [])
 * @method static HtmlElement object(array $attributes = [])
 * @method static HtmlElement ol(array $attributes = [])
 * @method static HtmlElement optgroup(array $attributes = [])
 * @method static HtmlElement option(array $attributes = [])
 * @method static HtmlElement output(array $attributes = [])
 * @method static HtmlElement p(array $attributes = [])
 * @method static HtmlElement pre(array $attributes = [])
 * @method static HtmlElement progress(array $attributes = [])
 * @method static HtmlElement q(array $attributes = [])
 * @method static HtmlElement rp(array $attributes = [])
 * @method static HtmlElement rt(array $attributes = [])
 * @method static HtmlElement ruby(array $attributes = [])
 * @method static HtmlElement s(array $attributes = [])
 * @method static HtmlElement samp(array $attributes = [])
 * @method static HtmlElement script(array $attributes = [])
 * @method static HtmlElement section(array $attributes = [])
 * @method static HtmlElement select(array $attributes = [])
 * @method static HtmlElement small(array $attributes = [])
 * @method static HtmlElement span(array $attributes = [])
 * @method static HtmlElement strong(array $attributes = [])
 * @method static HtmlElement style(array $attributes = [])
 * @method static HtmlElement sub(array $attributes = [])
 * @method static HtmlElement summary(array $attributes = [])
 * @method static HtmlElement sup(array $attributes = [])
 * @method static HtmlElement svg(array $attributes = [])
 * @method static HtmlElement table(array $attributes = [])
 * @method static HtmlElement tbody(array $attributes = [])
 * @method static HtmlElement td(array $attributes = [])
 * @method static HtmlElement textarea(array $attributes = [])
 * @method static HtmlElement tfoot(array $attributes = [])
 * @method static HtmlElement th(array $attributes = [])
 * @method static HtmlElement thead(array $attributes = [])
 * @method static HtmlElement time(array $attributes = [])
 * @method static HtmlElement title(array $attributes = [])
 * @method static HtmlElement tr(array $attributes = [])
 * @method static HtmlElement u(array $attributes = [])
 * @method static HtmlElement ul(array $attributes = [])
 * @method static HtmlElement var(array $attributes = [])
 * @method static HtmlElement video(array $attributes = [])
 */
class Html
{

    public static function __callStatic($method, $parameters): HtmlElement
    {
        return new HtmlElement($method, $parameters[0] ?? []);
    }

    public static function form(array $attributes = []): Form
    {
        return new Form($attributes);
    }

}